language: go
go_import_path: github.com/mushorg/go-dpi
install:
- sudo apt-get install git libpcap-dev autoconf automake autogen libtool
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get github.com/Masterminds/glide
- glide install
- git clone --branch 2.0-stable https://github.com/ntop/nDPI/ ~/nDPI
- cd ~/nDPI && ./autogen.sh && ./configure && make && sudo make install && cd -
script:
- go test . ./classifiers ./wrappers
- $HOME/gopath/bin/goveralls -ignore examples/example_app.go -service=travis-ci
